### ISSUE TITLE
ReflowAuth.getCookie needs to be made Async in Next JS 15

### ISSUE THREAD

**Issue by MrMoneyInTheBank** [Reflow-HQ/libs#1]
Hello,

I was working on password protecting a next js web application. I have used reflow in the past for this purpose and it has worked well for me. I once again tried to use it in my Next JS 15 application but this time I get a warning.

```zsh
Error: Route "/" used `cookies().get('session')`. `cookies()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at createCookiesAccessError (node_modules/next/src/server/request/cookies.ts:564:9)
    at getMessage (node_modules/next/src/server/create-deduped-by-callsite-server-error-logger.ts:46:20)
    at warnForSyncAccess (node_modules/next/src/server/request/cookies.ts:550:2)
    at syncIODev (node_modules/next/src/server/request/cookies.ts:424:8)
    at ReflowAuth.getCookie (node_modules/@reflowhq/auth-next/src/auth.ts:332:23)
    at ReflowAuth.all (node_modules/@reflowhq/auth-next/src/auth.ts:184:48)
    at getSession (src/lib/reflow/server-actions.ts:39:20)
    at Home (src/app/page.tsx:8:33)
  330 |   protected getCookie(): string {
  331 |     const cookieStore = cookies();
> 332 |     return cookieStore.get(this.cookieName)?.value ?? "";
      |                       ^
  333 |   }
  334 |
  335 |   protected setCookie(value: string) {
  ```
As per the next docs, cookies() is now an async function and must be awaited if called from a server component or be wrapped inside a React.use() if called from a client component. The current implementation will work for this version of next but may not work as expected in future versions.

**Comment by danny-mark** [comment]
Thanks for the heads up!

We added `async/await` to the `cookie()` calls: 234fb5d788d68e3cf57a0bbef64ec42b1ab4ef84

I tested with fresh Next 14 and Next 15 apps and it seems to work in both.
